var classes = [
    {
        "name": "Manager\\Notification\\Domain\\Builder\\PushEventBuilder",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "fromPlatform",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withReference",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withRepository",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withSender",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "withCommits",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "build",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 5,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Manager\\Notification\\Domain\\Type\\Platform",
            "Manager\\Notification\\Domain\\Type\\Reference",
            "Manager\\Notification\\Domain\\Entity\\Repository",
            "Manager\\Notification\\Domain\\Entity\\Sender",
            "Manager\\Notification\\Domain\\Type\\CommitCollection",
            "Manager\\Notification\\Domain\\Entity\\Event\\Push",
            "Manager\\Notification\\Domain\\Entity\\Event\\Push"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 36,
        "vocabulary": 8,
        "volume": 108,
        "difficulty": 4.17,
        "effort": 450,
        "level": 0.24,
        "bugs": 0.04,
        "time": 25,
        "intelligentContent": 25.92,
        "number_operators": 11,
        "number_operands": 25,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 39,
        "lloc": 39,
        "mi": 50.92,
        "mIwoC": 50.92,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 6.83,
        "relativeSystemComplexity": 6.83,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 41,
        "totalSystemComplexity": 41,
        "package": "Manager\\Notification\\Domain\\Builder\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 6,
        "instability": 0.86,
        "violations": {}
    },
    {
        "name": "Manager\\Notification\\Domain\\Type\\Author",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "nickName",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "email",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 6,
        "vocabulary": 4,
        "volume": 12,
        "difficulty": 0.67,
        "effort": 8,
        "level": 1.5,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 18,
        "number_operators": 2,
        "number_operands": 4,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 15,
        "lloc": 15,
        "mi": 66.65,
        "mIwoC": 66.65,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2.67,
        "relativeSystemComplexity": 2.67,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 8,
        "totalSystemComplexity": 8,
        "package": "Manager\\Notification\\Domain\\Type\\",
        "pageRank": 0.07,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Manager\\Notification\\Domain\\Type\\Reference",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "adjustTargetBranch",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "targetBranch",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "initialCommit",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "finalCommit",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 15,
        "vocabulary": 8,
        "volume": 45,
        "difficulty": 1.83,
        "effort": 82.5,
        "level": 0.55,
        "bugs": 0.02,
        "time": 5,
        "intelligentContent": 24.55,
        "number_operators": 4,
        "number_operands": 11,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 24,
        "lloc": 24,
        "mi": 58.18,
        "mIwoC": 58.18,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.8,
        "relativeSystemComplexity": 2.8,
        "totalStructuralComplexity": 5,
        "totalDataComplexity": 9,
        "totalSystemComplexity": 14,
        "package": "Manager\\Notification\\Domain\\Type\\",
        "pageRank": 0.06,
        "afferentCoupling": 3,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Manager\\Notification\\Domain\\Type\\Platform",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hash",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "name",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "url",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 9,
        "vocabulary": 5,
        "volume": 20.9,
        "difficulty": 0.75,
        "effort": 15.67,
        "level": 1.33,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 27.86,
        "number_operators": 3,
        "number_operands": 6,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 19,
        "lloc": 19,
        "mi": 62.73,
        "mIwoC": 62.73,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3.75,
        "relativeSystemComplexity": 3.75,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 15,
        "totalSystemComplexity": 15,
        "package": "Manager\\Notification\\Domain\\Type\\",
        "pageRank": 0.16,
        "afferentCoupling": 5,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Manager\\Notification\\Domain\\Type\\CommitCollection",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getIterator",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "count",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLast",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "IteratorAggregate",
            "Countable",
            "SplFixedArray",
            "Manager\\Notification\\Domain\\Entity\\Commit",
            "ArrayIterator",
            "ArrayIterator",
            "Manager\\Notification\\Domain\\Entity\\Commit"
        ],
        "parents": [],
        "implements": [
            "IteratorAggregate",
            "Countable"
        ],
        "lcom": 1,
        "length": 18,
        "vocabulary": 8,
        "volume": 54,
        "difficulty": 3.9,
        "effort": 210.6,
        "level": 0.26,
        "bugs": 0.02,
        "time": 12,
        "intelligentContent": 13.85,
        "number_operators": 5,
        "number_operands": 13,
        "number_operators_unique": 3,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 25,
        "lloc": 25,
        "mi": 57.24,
        "mIwoC": 57.24,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.9,
        "relativeSystemComplexity": 9.9,
        "totalStructuralComplexity": 45,
        "totalDataComplexity": 4.5,
        "totalSystemComplexity": 49.5,
        "package": "Manager\\Notification\\Domain\\Type\\",
        "pageRank": 0.06,
        "afferentCoupling": 3,
        "efferentCoupling": 5,
        "instability": 0.63,
        "violations": {}
    },
    {
        "name": "Manager\\Notification\\Domain\\Type\\Committer",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "nickName",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "email",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 6,
        "vocabulary": 4,
        "volume": 12,
        "difficulty": 0.67,
        "effort": 8,
        "level": 1.5,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 18,
        "number_operators": 2,
        "number_operands": 4,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 15,
        "lloc": 15,
        "mi": 66.65,
        "mIwoC": 66.65,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2.67,
        "relativeSystemComplexity": 2.67,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 8,
        "totalSystemComplexity": 8,
        "package": "Manager\\Notification\\Domain\\Type\\",
        "pageRank": 0.07,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Manager\\Notification\\Domain\\Entity\\Event\\Push",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "checkIfDeployable",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deployable",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "reference",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "platform",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "repository",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sender",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "commits",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 6,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Manager\\Notification\\Domain\\Type\\Reference",
            "Manager\\Notification\\Domain\\Type\\Platform",
            "Manager\\Notification\\Domain\\Entity\\Repository",
            "Manager\\Notification\\Domain\\Entity\\Sender",
            "Manager\\Notification\\Domain\\Type\\CommitCollection",
            "Manager\\Notification\\Domain\\Type\\Reference",
            "Manager\\Notification\\Domain\\Type\\Platform",
            "Manager\\Notification\\Domain\\Entity\\Repository",
            "Manager\\Notification\\Domain\\Entity\\Sender",
            "Manager\\Notification\\Domain\\Type\\CommitCollection"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 31,
        "vocabulary": 12,
        "volume": 111.13,
        "difficulty": 5,
        "effort": 555.67,
        "level": 0.2,
        "bugs": 0.04,
        "time": 31,
        "intelligentContent": 22.23,
        "number_operators": 11,
        "number_operands": 20,
        "number_operators_unique": 4,
        "number_operands_unique": 8,
        "cloc": 0,
        "loc": 39,
        "lloc": 39,
        "mi": 50.7,
        "mIwoC": 50.7,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 1.1,
        "relativeSystemComplexity": 26.1,
        "totalStructuralComplexity": 200,
        "totalDataComplexity": 8.83,
        "totalSystemComplexity": 208.83,
        "package": "Manager\\Notification\\Domain\\Entity\\Event\\",
        "pageRank": 0.06,
        "afferentCoupling": 4,
        "efferentCoupling": 5,
        "instability": 0.56,
        "violations": {}
    },
    {
        "name": "Manager\\Notification\\Domain\\Entity\\Sender",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "remoteId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "nickName",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "email",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "image",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 4,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 12,
        "vocabulary": 6,
        "volume": 31.02,
        "difficulty": 0.8,
        "effort": 24.82,
        "level": 1.25,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 38.77,
        "number_operators": 4,
        "number_operands": 8,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 23,
        "lloc": 23,
        "mi": 59.72,
        "mIwoC": 59.72,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 4.8,
        "relativeSystemComplexity": 4.8,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 24,
        "totalSystemComplexity": 24,
        "package": "Manager\\Notification\\Domain\\Entity\\",
        "pageRank": 0.06,
        "afferentCoupling": 3,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Manager\\Notification\\Domain\\Entity\\Owner",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "remoteId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "nickName",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "email",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "image",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 4,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 12,
        "vocabulary": 6,
        "volume": 31.02,
        "difficulty": 0.8,
        "effort": 24.82,
        "level": 1.25,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 38.77,
        "number_operators": 4,
        "number_operands": 8,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 23,
        "lloc": 23,
        "mi": 59.72,
        "mIwoC": 59.72,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 4.8,
        "relativeSystemComplexity": 4.8,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 24,
        "totalSystemComplexity": 24,
        "package": "Manager\\Notification\\Domain\\Entity\\",
        "pageRank": 0.08,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Manager\\Notification\\Domain\\Entity\\Repository",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "remoteId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "platform",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "owner",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "name",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cloneUrl",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "defaultBranch",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "description",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 7,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Manager\\Notification\\Domain\\Type\\Platform",
            "Manager\\Notification\\Domain\\Entity\\Owner",
            "Manager\\Notification\\Domain\\Type\\Platform",
            "Manager\\Notification\\Domain\\Entity\\Owner"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 21,
        "vocabulary": 9,
        "volume": 66.57,
        "difficulty": 0.88,
        "effort": 58.25,
        "level": 1.14,
        "bugs": 0.02,
        "time": 3,
        "intelligentContent": 76.08,
        "number_operators": 7,
        "number_operands": 14,
        "number_operators_unique": 1,
        "number_operands_unique": 8,
        "cloc": 0,
        "loc": 35,
        "lloc": 35,
        "mi": 53.42,
        "mIwoC": 53.42,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 7.88,
        "relativeSystemComplexity": 7.88,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 63,
        "totalSystemComplexity": 63,
        "package": "Manager\\Notification\\Domain\\Entity\\",
        "pageRank": 0.06,
        "afferentCoupling": 3,
        "efferentCoupling": 2,
        "instability": 0.4,
        "violations": {}
    },
    {
        "name": "Manager\\Notification\\Domain\\Entity\\Commit",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "checkIsMerge",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isMerge",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hash",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "message",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "author",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "commiter",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "platform",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "timestamp",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 7,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Manager\\Notification\\Domain\\Type\\Author",
            "Manager\\Notification\\Domain\\Type\\Committer",
            "Manager\\Notification\\Domain\\Type\\Platform",
            "Manager\\Notification\\Domain\\Type\\Author",
            "Manager\\Notification\\Domain\\Type\\Committer",
            "Manager\\Notification\\Domain\\Type\\Platform"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 28,
        "vocabulary": 12,
        "volume": 100.38,
        "difficulty": 3.17,
        "effort": 317.87,
        "level": 0.32,
        "bugs": 0.03,
        "time": 18,
        "intelligentContent": 31.7,
        "number_operators": 9,
        "number_operands": 19,
        "number_operators_unique": 3,
        "number_operands_unique": 9,
        "cloc": 0,
        "loc": 43,
        "lloc": 43,
        "mi": 50.22,
        "mIwoC": 50.22,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 1.53,
        "relativeSystemComplexity": 17.53,
        "totalStructuralComplexity": 144,
        "totalDataComplexity": 13.8,
        "totalSystemComplexity": 157.8,
        "package": "Manager\\Notification\\Domain\\Entity\\",
        "pageRank": 0.06,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "Manager\\Notification\\Infra\\Persistence\\PushEventPersister",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "persist",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 9,
        "ccnMethodMax": 9,
        "externals": [
            "Manager\\Notification\\Domain\\Entity\\Event\\Push",
            "DB",
            "DB",
            "DB",
            "DB",
            "DB",
            "DB",
            "DB",
            "DB",
            "DB",
            "DB",
            "DB"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 127,
        "vocabulary": 34,
        "volume": 646.11,
        "difficulty": 5.32,
        "effort": 3438.96,
        "level": 0.19,
        "bugs": 0.22,
        "time": 191,
        "intelligentContent": 121.39,
        "number_operators": 17,
        "number_operands": 110,
        "number_operators_unique": 3,
        "number_operands_unique": 31,
        "cloc": 0,
        "loc": 30,
        "lloc": 30,
        "mi": 46.89,
        "mIwoC": 46.89,
        "commentWeight": 0,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 529,
        "relativeDataComplexity": 0.13,
        "relativeSystemComplexity": 529.13,
        "totalStructuralComplexity": 529,
        "totalDataComplexity": 0.13,
        "totalSystemComplexity": 529.13,
        "package": "Manager\\Notification\\Infra\\Persistence\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Manager\\Notification\\Infra\\Service\\GitHubSignatureVerificationService",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasValidSignature",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "verify",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Illuminate\\Http\\Request",
            "Illuminate\\Http\\Request"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 26,
        "vocabulary": 13,
        "volume": 96.21,
        "difficulty": 3.78,
        "effort": 363.47,
        "level": 0.26,
        "bugs": 0.03,
        "time": 20,
        "intelligentContent": 25.47,
        "number_operators": 9,
        "number_operands": 17,
        "number_operators_unique": 4,
        "number_operands_unique": 9,
        "cloc": 0,
        "loc": 25,
        "lloc": 25,
        "mi": 55.35,
        "mIwoC": 55.35,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.22,
        "relativeSystemComplexity": 5.22,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 3.67,
        "totalSystemComplexity": 15.67,
        "package": "Manager\\Notification\\Infra\\Service\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Manager\\Notification\\Infra\\Service\\GitHubEventTypeService",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "getEventType",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "verifyHeader",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Illuminate\\Http\\Request",
            "Illuminate\\Http\\Request",
            "Exception"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 14,
        "vocabulary": 9,
        "volume": 44.38,
        "difficulty": 2.75,
        "effort": 122.04,
        "level": 0.36,
        "bugs": 0.01,
        "time": 7,
        "intelligentContent": 16.14,
        "number_operators": 3,
        "number_operands": 11,
        "number_operators_unique": 3,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 17,
        "lloc": 17,
        "mi": 61.36,
        "mIwoC": 61.36,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 4.67,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 1.33,
        "totalSystemComplexity": 9.33,
        "package": "Manager\\Notification\\Infra\\Service\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Manager\\Notification\\Infra\\Controller\\GitHubPushEventController",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 5,
        "ccnMethodMax": 5,
        "externals": [
            "Illuminate\\Http\\Request",
            "Manager\\Notification\\Application\\Factory\\GitHubEventInputFactory",
            "Manager\\Notification\\Application\\UseCase\\RegisterPushEvent",
            "Illuminate\\Http\\JsonResponse",
            "Illuminate\\Http\\JsonResponse",
            "Illuminate\\Http\\JsonResponse"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 48,
        "vocabulary": 19,
        "volume": 203.9,
        "difficulty": 6.07,
        "effort": 1237.97,
        "level": 0.16,
        "bugs": 0.07,
        "time": 69,
        "intelligentContent": 33.58,
        "number_operators": 14,
        "number_operands": 34,
        "number_operators_unique": 5,
        "number_operands_unique": 14,
        "cloc": 0,
        "loc": 25,
        "lloc": 25,
        "mi": 52.66,
        "mIwoC": 52.66,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.58,
        "relativeSystemComplexity": 25.58,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 1.17,
        "totalSystemComplexity": 51.17,
        "package": "Manager\\Notification\\Infra\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Manager\\Notification\\Infra\\Middleware\\GitHubAttachEventTypeOnRequestDataMiddleware",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Manager\\Notification\\Infra\\Service\\GitHubEventTypeService",
            "Illuminate\\Http\\Request",
            "Closure",
            "Illuminate\\Http\\JsonResponse"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 16,
        "vocabulary": 9,
        "volume": 50.72,
        "difficulty": 1.86,
        "effort": 94.19,
        "level": 0.54,
        "bugs": 0.02,
        "time": 5,
        "intelligentContent": 27.31,
        "number_operators": 3,
        "number_operands": 13,
        "number_operators_unique": 2,
        "number_operands_unique": 7,
        "cloc": 0,
        "loc": 16,
        "lloc": 16,
        "mi": 61.52,
        "mIwoC": 61.52,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.7,
        "relativeSystemComplexity": 16.7,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 1.4,
        "totalSystemComplexity": 33.4,
        "package": "Manager\\Notification\\Infra\\Middleware\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Manager\\Notification\\Infra\\Middleware\\GitHubSignatureVerifyMiddleware",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Manager\\Notification\\Infra\\Service\\GitHubSignatureVerificationService",
            "Illuminate\\Http\\Request",
            "Closure",
            "Illuminate\\Http\\JsonResponse",
            "Illuminate\\Http\\JsonResponse"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 20,
        "vocabulary": 11,
        "volume": 69.19,
        "difficulty": 1.67,
        "effort": 115.31,
        "level": 0.6,
        "bugs": 0.02,
        "time": 6,
        "intelligentContent": 41.51,
        "number_operators": 5,
        "number_operands": 15,
        "number_operators_unique": 2,
        "number_operands_unique": 9,
        "cloc": 0,
        "loc": 17,
        "lloc": 17,
        "mi": 59.87,
        "mIwoC": 59.87,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 5.5,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 11,
        "package": "Manager\\Notification\\Infra\\Middleware\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Manager\\Notification\\Application\\Output",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 2,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 7,
        "lloc": 7,
        "mi": 79.32,
        "mIwoC": 79.32,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "package": "Manager\\Notification\\Application\\",
        "pageRank": 0.05,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Manager\\Notification\\Application\\UseCase\\RegisterPushEvent",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Manager\\Notification\\Infra\\Persistence\\PushEventPersister",
            "Manager\\Notification\\Application\\Output",
            "Manager\\Notification\\Domain\\Entity\\Event\\Push",
            "Manager\\Notification\\Application\\Output",
            "Manager\\Notification\\Application\\Output"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 11,
        "vocabulary": 8,
        "volume": 33,
        "difficulty": 1.33,
        "effort": 44,
        "level": 0.75,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 24.75,
        "number_operators": 3,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 1,
        "loc": 17,
        "lloc": 16,
        "mi": 81.18,
        "mIwoC": 62.83,
        "commentWeight": 18.35,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 10,
        "package": "Manager\\Notification\\Application\\UseCase\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "Manager\\Notification\\Application\\Factory\\GitHubEventInputFactory",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createPushEvent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createPlatform",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createReference",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createRepository",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createSender",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createCommits",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createCommit",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 6,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 4,
        "ccnMethodMax": 2,
        "externals": [
            "Manager\\Notification\\Domain\\Builder\\PushEventBuilder",
            "Manager\\Notification\\Domain\\Entity\\Event\\Push",
            "Manager\\Notification\\Domain\\Type\\Platform",
            "Manager\\Notification\\Domain\\Type\\Reference",
            "Exception",
            "Manager\\Notification\\Domain\\Entity\\Owner",
            "Manager\\Notification\\Domain\\Entity\\Repository",
            "Manager\\Notification\\Domain\\Entity\\Sender",
            "Manager\\Notification\\Domain\\Type\\CommitCollection",
            "Manager\\Notification\\Domain\\Entity\\Commit",
            "Manager\\Notification\\Domain\\Type\\Author",
            "Manager\\Notification\\Domain\\Type\\Committer",
            "Manager\\Notification\\Domain\\Entity\\Commit"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 147,
        "vocabulary": 36,
        "volume": 759.98,
        "difficulty": 10,
        "effort": 7599.79,
        "level": 0.1,
        "bugs": 0.25,
        "time": 422,
        "intelligentContent": 76,
        "number_operators": 23,
        "number_operands": 124,
        "number_operators_unique": 5,
        "number_operands_unique": 31,
        "cloc": 0,
        "loc": 59,
        "lloc": 59,
        "mi": 40.66,
        "mIwoC": 40.66,
        "commentWeight": 0,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 169,
        "relativeDataComplexity": 0.53,
        "relativeSystemComplexity": 169.53,
        "totalStructuralComplexity": 1352,
        "totalDataComplexity": 4.21,
        "totalSystemComplexity": 1356.21,
        "package": "Manager\\Notification\\Application\\Factory\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 12,
        "instability": 0.92,
        "violations": {}
    }
]